<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\FieldConfigInterface;


/*
**/
function wco_drupal_theme_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {

  $form['load_libraries'] = [
    '#type' => 'checkboxes',
    '#title' => t('Load libraries'),
    '#options' => [
      'mavericks' => 'mavericks',
    ],
    '#default_value' => theme_get_setting('load_libraries') ?? [],
    '#description' => t('Selected libraries will be loaded on all pages.'),
  ];

  $form['field_custom_css'] = [
    '#type' => 'textarea',
    '#title' => t('Custom CSS'),
    '#default_value' => theme_get_setting('field_custom_css'),
    '#description' => t('Custom CSS for this theme.'),
  ];

  $form['footer_image_hero'] = [
    '#type' => 'managed_file',
    '#title' => t('Footer hero image'),
    '#upload_location' => 'public://theme/footer',
    '#default_value' => theme_get_setting('footer_image_hero'),
    '#upload_validators' => [
      'FileExtension' => [
        'extensions' => 'png jpg jpeg webp',
      ],
    ],
  ];

}





function wco_drupal_theme_preprocess_node(array &$variables) {
  $node = $variables['node'];

  if ($variables['view_mode'] == 'full') {
    if ($node->hasField('field_image_hero')) {

      $field_image_hero = $node->get('field_image_hero');
      $image_hero = NULL;
      if (!$field_image_hero->isEmpty()) {
        $image_hero = $field_image_hero->entity;
      } else {
        $definition = $field_image_hero->getFieldDefinition();
        $default_image = $definition->getSetting('default_image');
        if (empty($default_image['uuid']) && $definition instanceof FieldConfigInterface) {
          $default_image = $definition->getFieldStorageDefinition()->getSetting('default_image');
        }
        if (!empty($default_image['uuid'])) {
          $image_hero = \Drupal::service('entity.repository')->loadEntityByUuid('file', $default_image['uuid']);
        }
      }
      if ($image_hero) {
        $variables['image_hero_url'] = \Drupal::service('file_url_generator')
          ->generateString($image_hero->getFileUri());
      }

    }
  }
}

/*
 * Implements hook_preprocess_HOOK() for page templates.
**/
function wco_drupal_theme_preprocess_page(array &$variables) {
  $config = \Drupal::config('wco_drupal_theme.settings');
  $libraries = $config->get('load_libraries') ?? [];
  foreach ($libraries as $library => $value) {
    if ($value) {
      $attachments['#attached']['library'][] = "wco_drupal_theme/{$library}";
    }
  }

  $variables['theme_custom_css'] = theme_get_setting('field_custom_css');

  $footer_image_hero = theme_get_setting('footer_image_hero');
  if ($footer_image_hero) {
    if (is_array($footer_image_hero)) {
      $footer_image_hero = reset($footer_image_hero);
    }
    $file = \Drupal\file\Entity\File::load($footer_image_hero);
    if ($file) {
      $variables['footer_image_hero'] = $file->createFileUrl();
    }
  }
}
